pCenter:
  euler: [0.0, 0.0, 0.0]
  pos: [0.0, 0.0, 0.0]
pFlaw:
  euler: [0.0, 0.0, 0.0]
  pos: [0.0, 0.0, 0.0]
pHome:
  euler: [1.0, 0.0, 0.0]
  pos: [0.0, 0.0, 0.0]
pNFlaw:
  euler: [0.0, 0.0, 0.0]
  pos: [0.0, 0.0, 0.0]
