error_height: 12
pBoard:
- euler: [0, 0, 0]
  pos: [0, 0, 0]
- euler: [0, 0, 0]
  pos: [0, 1.125, 0]
- euler: [0, 0, 0]
  pos: [0, 2.25, 0]
- euler: [0, 0, 0]
  pos: [0, 3.375, 0]
- euler: [0, 0, 0]
  pos: [0, 4.5, 0]
- euler: [0, 0, 0]
  pos: [0, 5.625, 0]
- euler: [0, 0, 0]
  pos: [0, 6.75, 0]
- euler: [0, 0, 0]
  pos: [0, 7.875, 0]
- euler: [0, 0, 0]
  pos: [0, 9, 0]
- euler: [0, 0, 0]
  pos: [1.125, 0, 0]
- euler: [0, 0, 0]
  pos: [1.125, 1.125, 0]
- euler: [0, 0, 0]
  pos: [1.125, 2.25, 0]
- euler: [0, 0, 0]
  pos: [1.125, 3.375, 0]
- euler: [0, 0, 0]
  pos: [1.125, 4.5, 0]
- euler: [0, 0, 0]
  pos: [1.125, 5.625, 0]
- euler: [0, 0, 0]
  pos: [1.125, 6.75, 0]
- euler: [0, 0, 0]
  pos: [1.125, 7.875, 0]
- euler: [0, 0, 0]
  pos: [1.125, 9, 0]
- euler: [0, 0, 0]
  pos: [2.25, 0, 0]
- euler: [0, 0, 0]
  pos: [2.25, 1.125, 0]
- euler: [0, 0, 0]
  pos: [2.25, 2.25, 0]
- euler: [0, 0, 0]
  pos: [2.25, 3.375, 0]
- euler: [0, 0, 0]
  pos: [2.25, 4.5, 0]
- euler: [0, 0, 0]
  pos: [2.25, 5.625, 0]
- euler: [0, 0, 0]
  pos: [2.25, 6.75, 0]
- euler: [0, 0, 0]
  pos: [2.25, 7.875, 0]
- euler: [0, 0, 0]
  pos: [2.25, 9, 0]
- euler: [0, 0, 0]
  pos: [3.375, 0, 0]
- euler: [0, 0, 0]
  pos: [3.375, 1.125, 0]
- euler: [0, 0, 0]
  pos: [3.375, 2.25, 0]
- euler: [0, 0, 0]
  pos: [3.375, 3.375, 0]
- euler: [0, 0, 0]
  pos: [3.375, 4.5, 0]
- euler: [0, 0, 0]
  pos: [3.375, 5.625, 0]
- euler: [0, 0, 0]
  pos: [3.375, 6.75, 0]
- euler: [0, 0, 0]
  pos: [3.375, 7.875, 0]
- euler: [0, 0, 0]
  pos: [3.375, 9, 0]
- euler: [0, 0, 0]
  pos: [4.5, 0, 0]
- euler: [0, 0, 0]
  pos: [4.5, 1.125, 0]
- euler: [0, 0, 0]
  pos: [4.5, 2.25, 0]
- euler: [0, 0, 0]
  pos: [4.5, 3.375, 0]
- euler: [0, 0, 0]
  pos: [4.5, 4.5, 0]
- euler: [0, 0, 0]
  pos: [4.5, 5.625, 0]
- euler: [0, 0, 0]
  pos: [4.5, 6.75, 0]
- euler: [0, 0, 0]
  pos: [4.5, 7.875, 0]
- euler: [0, 0, 0]
  pos: [4.5, 9, 0]
- euler: [0, 0, 0]
  pos: [5.625, 0, 0]
- euler: [0, 0, 0]
  pos: [5.625, 1.125, 0]
- euler: [0, 0, 0]
  pos: [5.625, 2.25, 0]
- euler: [0, 0, 0]
  pos: [5.625, 3.375, 0]
- euler: [0, 0, 0]
  pos: [5.625, 4.5, 0]
- euler: [0, 0, 0]
  pos: [5.625, 5.625, 0]
- euler: [0, 0, 0]
  pos: [5.625, 6.75, 0]
- euler: [0, 0, 0]
  pos: [5.625, 7.875, 0]
- euler: [0, 0, 0]
  pos: [5.625, 9, 0]
- euler: [0, 0, 0]
  pos: [6.75, 0, 0]
- euler: [0, 0, 0]
  pos: [6.75, 1.125, 0]
- euler: [0, 0, 0]
  pos: [6.75, 2.25, 0]
- euler: [0, 0, 0]
  pos: [6.75, 3.375, 0]
- euler: [0, 0, 0]
  pos: [6.75, 4.5, 0]
- euler: [0, 0, 0]
  pos: [6.75, 5.625, 0]
- euler: [0, 0, 0]
  pos: [6.75, 6.75, 0]
- euler: [0, 0, 0]
  pos: [6.75, 7.875, 0]
- euler: [0, 0, 0]
  pos: [6.75, 9, 0]
- euler: [0, 0, 0]
  pos: [7.875, 0, 0]
- euler: [0, 0, 0]
  pos: [7.875, 1.125, 0]
- euler: [0, 0, 0]
  pos: [7.875, 2.25, 0]
- euler: [0, 0, 0]
  pos: [7.875, 3.375, 0]
- euler: [0, 0, 0]
  pos: [7.875, 4.5, 0]
- euler: [0, 0, 0]
  pos: [7.875, 5.625, 0]
- euler: [0, 0, 0]
  pos: [7.875, 6.75, 0]
- euler: [0, 0, 0]
  pos: [7.875, 7.875, 0]
- euler: [0, 0, 0]
  pos: [7.875, 9, 0]
- euler: [0, 0, 0]
  pos: [9, 0, 0]
- euler: [0, 0, 0]
  pos: [9, 1.125, 0]
- euler: [0, 0, 0]
  pos: [9, 2.25, 0]
- euler: [0, 0, 0]
  pos: [9, 3.375, 0]
- euler: [0, 0, 0]
  pos: [9, 4.5, 0]
- euler: [0, 0, 0]
  pos: [9, 5.625, 0]
- euler: [0, 0, 0]
  pos: [9, 6.75, 0]
- euler: [0, 0, 0]
  pos: [9, 7.875, 0]
- euler: [0, 0, 0]
  pos: [9, 9, 0]
pBoardCenter:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pButton:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pChess:
  euler: [0, 0, 0]
  pos: [0, 1, 0]
pHome:
  euler: [0, 0, 0]
  pos: [12, 0, 0]
