checkROI: 0
pCamLeft:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pCamRight:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pCenter:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pFront:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pHead:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pHome:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pLeftWing:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pRear:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pRightWing:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pSuction:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pTail:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pixelRate: 0
rollObject: {front: 0, head: 0, leftWing: 0, rear: 0, rightWing: 0, tail: 0}
score_threshold: 0
