checkROI: 100
euler: [0, 0, 0]
flaw_threshold: 1000
pCenter:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pFlaw:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pHome:
  euler: [0, 0, 0]
  pos: [12, 0, 0]
pNFlaw:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pSuction:
  euler: [0, 0, 0]
  pos: [0, 0, 0]
pixelRate: 0.2
pos: [12, 0, 0]
score_threshold: 0.5
slideX: 130
slideY: 30
slideZ: 10
